on:
  workflow_call:
    inputs:
        environment:
            required: true
            type: string
        aws-account:
            required: true
            type: string
        
name: Deploy Lambda

jobs:
  build:
    name: Build Lambda
    runs-on: ubuntu-latest

  
    permissions:
      contents: read
      id-token: write
  
    steps:
      - name: Checkout Repo  
        uses: actions/checkout@v4
  
      # https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#publishing-using-apache-maven
      - name: Setup Java (GraalVM)
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm-community'
          cache: maven

      - name: Build and Package
        run: mvn clean -Pnative package -DskipTests

      - uses: aws-actions/setup-sam@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ inputs.aws-account }}:role/Lambda.Role
          aws-region: us-east-1
  
      - name: Package
        run: sam package --s3-bucket com.hoopladigital.lambda --s3-prefix hoopla-api-token --output-template-file packaged.yaml
  
      - name: Deploy
        run: sam deploy --template-file packaged.yaml --region us-east-1 --config-file samconfig.toml
