name: Deploy Lambda

on:
  workflow_call:
    inputs:
      role_name:
        description: 'Assumable AWS IAM role name'
        required: true
        type: string
      region:
        description: 'AWS region'
        required: true
        type: string
      zip_path:
        description: 'Zip archive path'
        required: true
        type: string
      function_name:
        description: 'Lambda function name'
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ inputs.role_name }}
          role-session-name: GitHubActions
          aws-region: ${{ inputs.region }}

      - name: STS GetCallerIdentity
        run: |
          aws sts get-caller-identity

      - name: Deploy Lambda function
        run: |
          aws lambda update-function-code \
            --function-name "${{ inputs.function_name }}" \
            --zip-file "fileb://${{ inputs.zip_path }}" \
            --publish
